### ISSUE TITLE
Unlabeled dataset went to size of 0 suddenly for customize symmetric noise ratio setting on cifar10 dataset

### ISSUE THREAD

**Issue by Xinyu-ustc** [KentoNishi/Augmentation-for-LNL#2]
I try to set the symmetric noise ratio to 0.94 and use the 90sym setting in presets.json. After around 50 epochs, the unlabeled dataset of net2 go to size 0 while for net1 the unlabeled dataset size is around 43000. In contrast, during the last epoch before collapse, the unlabeled dataset size for net1 and net2 are both around 43000. Do you have any suggestions on why this happen how to solve this issue? Thanks!

**Comment by KentoNishi** [comment]
Thanks for reaching out!

The reason that this fails is most likely because the noise ratio of 0.94 is simply too high. In my personal experience training dividemix using augdesc, it seems that the loss bimodality assumption is not met as the difficulty of the dataset increases. Therefore, the filtering becomes increasingly lopsided over time, until it eventually collapses. If you would like, I have committed additional tools to plot the loss distributions over time in the [Aug-for-LNL-Extras repo](https://github.com/KentoNishi/Aug-for-LNL-Extras), so you could try plotting the curves to see what exactly is causing the collapse!

Below is what the distribution for 80% noise looks like over time:
![animated_80](https://user-images.githubusercontent.com/38841491/126268294-f21c5c98-1045-4de0-b8a3-31d3b8cfda45.gif)

I'm very interested to see how such a high noise ratio performs as well, so if you do give it a go, please let me know!

**Comment by Xinyu-ustc** [comment]
Thanks! Will have a try.
